### PR TITLE
Added ToS accepting before log in (with help from Noel <3)

### LINKED ISSUE #60: Implement forced TOS accepting before log in
People who haven't acccepted the TOS can still log in, which creates a lot of issues

### PR DESCRIPTION
**Pull request by SuperVK**
Fixes #60

### CODE REVIEW

**Review by CodeNamedRobin — APPROVED** [review]
LGTM!

**Comment by SuperVK** [comment]
Added ToS accepting using frontend-common functions, now requires this [pull request](https://github.com/GEWIS/sudosos-frontend-common/pull/3) to be merged first!

(Should also be why the checks are failing)

**Comment by SuperVK** [comment]
Oh and this also fixes the issue where if you reload, your balance doesn't update. The issue was `populateStoresFrom()` didn't include `populateStoresFrom(apiService)`

**Review by JustSamuel — APPROVED** [review]
lgtm

**Pull request merged**
