### PR TITLE
Refactor(dashboard): forms

### PR DESCRIPTION
**Pull request by JustSamuel**
# Description
This PR provides an example and implementation of a new way to structure form creation.

## Related issues/external references
#216 
#15 

## Types of changes
- New feature _(non-breaking change which adds functionality)_

### CODE REVIEW

**Comment by JustSamuel** [comment]
@SuperVK @CodeNamedRobin This PR is also for discussion.

Any suggestions on moving the submission code to the form component? I think we can also generalize the creating of toasts.

**Review by SuperVK — APPROVED** [review]
I see the benefit in it, I would like to see an issue that tracks all the places where this is needed, otherwise we get even more random different implementations.

**Review by SuperVK — APPROVED** [review]
I see the benefit in it, I would like to see an issue that tracks all the places where this is needed, otherwise we get even more random different implementations.

**Comment by SuperVK** [comment]
Thank you Github

**Pull request closed without merging**
