### PR TITLE
Feature/sudososversion

### LINKED ISSUE #279: Show version of SudoSOS in the footer of the website
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Dashboard

### What would you like?

I´d like to be able to see what version (either a version number or a commit hash) the website is on. 

### Why is this needed?

This is inspired by #276, which should have been fixed in #165. As the issue is fixed in sudosos.test.gewis.nl  and not on sudosos.gewis.nl, I would like to see what version is running where. This way it is possible to see whether the issue persists because of not releasing the next version of SudoSOS or because it is still broken.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by BHenkemans**
# Description

This shows what commit the website is on. Since this is really not vital information for everyone, it is hidden behind the copyright on the bottom of the page.

Screencast_20240731_201754

## Related issues/external references

Resolves GH-279

## Types of changes

- New feature _(non-breaking change which adds functionality)_

### CODE REVIEW

**Review by CodeNamedRobin — APPROVED** [review]

**Comment by BHenkemans** [comment]
All good and well, but during the GitHub Action the .git is ignored (which makes sense, but for me is somewhat of an inconvenience...)

**Comment by tomudding** [comment]
> All good and well, but during the GitHub Action the .git is ignored (which makes sense, but for me is somewhat of an inconvenience...)

Is it ignored or is your plugin just executed from the wrong directory?

**Comment by SuperVK** [comment]
Dockerfile from the POS does copy the .git folder, dashboard does not so i guess that explains the issue?

**Comment by BHenkemans** [comment]
> Dockerfile from the POS does copy the .git folder, dashboard does not so i guess that explains the issue?

It does, but it is kind of a bad habit to copy the .git folder into your image. @tomudding and I discussed another option.

**Comment by BHenkemans** [comment]
In short, the idea is, instead of copying the .git repository and letting vite figure out with git command what the branch and commit hash is, you let the GitHub Action pass the branch and commit as a Docker arg which then adds it into the website. 

Pro: Don´t have to copy the .git folder into your image

Con: Locally, you wont be able to see the version. But in all honesty, that is not really necessary anyway (you probably have another way of knowing on what branch you are while working locally). 

@SuperVK @CodeNamedRobin thoughts?

**Comment by SuperVK** [comment]
Yeah probably cleaner, could you also fix the POS workflow while you are at it? :)

**Comment by BHenkemans** [comment]
> Yeah probably cleaner, could you also fix the POS workflow while you are at it? :)

Sure, but I will make another issue for this

**Pull request merged**
