### PR TITLE
Bugfix/container products improvements

### LINKED ISSUE #102: Unable to remove products from container

### LINKED ISSUE #103: Unable to change image of a product

### PR DESCRIPTION
**Pull request by SuperVK**
Fixes #102 and fixes #103

### CODE REVIEW

**Comment by CodeNamedRobin** [comment]
Product images right now are not cropped to be square, leading to labels not appearing.

**Comment by CodeNamedRobin** [comment]
Horizontal Scrolling on container tabs doesn't work anymore.

**Comment by SuperVK** [comment]
> Horizontal Scrolling on container tabs doesn't work anymore.

Doesn't work on develop either :( @CodeNamedRobin

**Review by CodeNamedRobin — APPROVED** [review]
LGTM!

**Pull request merged**
